channels:
- conda-forge
- bioconda
dependencies:
- fastqc=0.11.6
- sra-tools=2.8
- snakemake-minimal=5.3.0
- multiqc=1.3
- bowtie2=2.3
- samtools=1.6
- htseq=0.9
- graphviz=2.38.0
- xorg-libxrender
- xorg-libxpm
- r-ggplot2=3.1.1
- r-reshape2=1.4.3
- r-pheatmap=1.0.12
- bioconductor-rtracklayer=1.42.1
- bioconductor-geoquery=2.50.5
- r-rmarkdown=1.12
